version: 2.1

orbs:
  maven: drift/maven@0.1.13

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - maven/build-jar
workflows:
  example-workflow:
    jobs:
      - example-job