version: 2.1

orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

workflows:
    example-workflow:
      jobs:
        - circleci-maven-release-orb/run-maven-release